# Generated by Django 5.2.7 on 2026-06-05 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('motivated', 'Motivated'), ('sleepy', 'Sleepy'), ('burned_out', 'Burned Out'), ('lazy', 'Lazy'), ('existential_crisis', 'Existential Crisis')], help_text="User's current mood", max_length=50)),
                ('interests', models.JSONField(default=list, help_text='List of user interests (YouTube, AI, Gaming, etc.)')),
                ('tasks', models.JSONField(default=list, help_text='List of tasks user planned to do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(auto_now_add=True, help_text='Date of the report')),
                ('tasks_planned', models.IntegerField(default=0, help_text='Number of tasks user planned')),
                ('tasks_completed', models.IntegerField(default=0, help_text='Number of tasks completed')),
                ('total_disappearances', models.IntegerField(default=0, help_text='Total number of disappearances')),
                ('procrastination_score', models.IntegerField(default=0, help_text='Procrastination score (0-100)')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated procrastination report summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='Session this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='procrastina_ai.session')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Disappearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disappearance_type', models.CharField(choices=[('youtube', 'Watching YouTube'), ('laptops', 'Looking At Laptops'), ('ai_tools', 'Researching AI Tools'), ('startup', 'Planning A Startup'), ('comments', 'Reading Comments'), ('other', 'Other (custom location)')], help_text='Where the user disappeared to', max_length=100)),
                ('custom_location', models.CharField(blank=True, help_text="Custom location if 'other' was selected", max_length=255, null=True)),
                ('ai_response', models.TextField(blank=True, help_text='AI-generated witty response about the disappearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='Session this disappearance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='disappearances', to='procrastina_ai.session')),
            ],
            options={
                'verbose_name': 'Disappearance',
                'verbose_name_plural': 'Disappearances',
                'ordering': ['-created_at'],
            },
        ),
    ]
