# Generated by Django 5.2.7 on 2026-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether the session is currently active (ended via 'Stop My Day')"),
        ),
    ]
