# Generated by Django 5.2.7 on 2026-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0002_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active_seconds',
            field=models.FloatField(default=0, help_text='Total seconds of detected browser activity (mousemove, click, keydown, scroll)'),
        ),
        migrations.AddField(
            model_name='session',
            name='activity_data_sufficient',
            field=models.BooleanField(default=False, help_text='Whether enough activity data was collected for accurate reporting'),
        ),
        migrations.AddField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when session was ended via 'Stop My Day'", null=True),
        ),
    ]
