# Generated by Django 5.2.7 on 2026-06-05 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0003_session_active_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('desktop_agent', 'Python Desktop Agent'), ('browser_extension', 'Browser Extension'), ('mobile_app', 'Mobile App'), ('manual_api', 'Manual API (testing)')], help_text='What sent this activity data', max_length=30)),
                ('client_version', models.CharField(blank=True, default='', help_text='Version of the desktop agent or browser extension', max_length=50)),
                ('platform', models.CharField(blank=True, default='', help_text='OS platform: windows, macos, linux', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When tracking started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When tracking ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this activity session is still running')),
                ('total_active_seconds', models.FloatField(default=0, help_text='Total seconds of active usage across all apps/websites')),
                ('total_idle_seconds', models.FloatField(default=0, help_text='Total seconds of detected idle time')),
                ('event_count', models.IntegerField(default=0, help_text='Total number of activity events received')),
                ('session', models.ForeignKey(help_text='Parent manual session', on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='procrastina_ai.session')),
            ],
            options={
                'verbose_name': 'Activity Session',
                'verbose_name_plural': 'Activity Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IdlePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idle_type', models.CharField(choices=[('no_input', 'No keyboard/mouse input'), ('screen_locked', 'Screen locked'), ('system_sleep', 'System sleep/hibernate'), ('away', 'User away (manual)')], default='no_input', help_text='Reason this period was classified as idle', max_length=20)),
                ('started_at', models.DateTimeField(help_text='When idle period started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When idle period ended (null if still idle)', null=True)),
                ('duration_seconds', models.FloatField(default=0, help_text='Total duration of idle period in seconds')),
                ('last_active_app', models.CharField(blank=True, default='', help_text='Application that was focused before idle started', max_length=255)),
                ('last_active_domain', models.CharField(blank=True, default='', help_text='Website that was active before idle started', max_length=255)),
                ('activity_session', models.ForeignKey(help_text='Activity session this idle period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='idle_periods', to='procrastina_ai.activitysession')),
            ],
            options={
                'verbose_name': 'Idle Period',
                'verbose_name_plural': 'Idle Periods',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('app_focus', 'Application Focused'), ('app_blur', 'Application Blurred'), ('website_visit', 'Website Visited'), ('website_leave', 'Website Left'), ('input_detected', 'Input Activity Detected'), ('window_change', 'Window Changed'), ('system_event', 'System Event (lock, sleep, etc.)')], help_text='Type of activity event', max_length=30)),
                ('target_name', models.CharField(help_text='Application name or website domain', max_length=255)),
                ('category', models.CharField(choices=[('productivity', 'Productivity (VS Code, Notion, etc.)'), ('development', 'Development (IDE, Terminal, Git)'), ('communication', 'Communication (Slack, Email, Discord)'), ('social', 'Social Media (Instagram, Twitter, Reddit)'), ('entertainment', 'Entertainment (YouTube, Netflix, Gaming)'), ('ai_tools', 'AI Tools (ChatGPT, Claude, etc.)'), ('browsing', 'General Browsing'), ('system', 'System (Desktop, File Explorer)'), ('other', 'Other')], default='other', help_text='Category of the target application/website', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data: window title, URL path, process name, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this event occurred')),
                ('duration_seconds', models.FloatField(default=0, help_text='How long this event lasted (if applicable)')),
                ('activity_session', models.ForeignKey(help_text='Activity session this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='procrastina_ai.activitysession')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['activity_session', 'event_type'], name='procrastina_activit_487ad7_idx'), models.Index(fields=['target_name', 'category'], name='procrastina_target__fb6284_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(help_text="Application name (e.g., 'Visual Studio Code', 'Chrome')", max_length=255)),
                ('app_process', models.CharField(blank=True, default='', help_text="Process name (e.g., 'code.exe', 'chrome.exe')", max_length=255)),
                ('category', models.CharField(choices=[('productivity', 'Productivity (VS Code, Notion, etc.)'), ('development', 'Development (IDE, Terminal, Git)'), ('communication', 'Communication (Slack, Email, Discord)'), ('social', 'Social Media (Instagram, Twitter, Reddit)'), ('entertainment', 'Entertainment (YouTube, Netflix, Gaming)'), ('ai_tools', 'AI Tools (ChatGPT, Claude, etc.)'), ('browsing', 'General Browsing'), ('system', 'System (Desktop, File Explorer)'), ('other', 'Other')], default='other', help_text='Category of this application', max_length=30)),
                ('total_seconds', models.FloatField(default=0, help_text='Total time spent in this application (seconds)')),
                ('focus_events', models.IntegerField(default=0, help_text='Number of times user focused this app')),
                ('first_seen', models.DateTimeField(blank=True, help_text='First time this app was focused', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time this app was focused', null=True)),
                ('activity_session', models.ForeignKey(help_text='Activity session this usage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='application_usage', to='procrastina_ai.activitysession')),
            ],
            options={
                'verbose_name': 'Application Usage',
                'verbose_name_plural': 'Application Usages',
                'ordering': ['-total_seconds'],
                'unique_together': {('activity_session', 'app_name')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text="Website domain (e.g., 'youtube.com', 'instagram.com')", max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text="Page title (e.g., 'Cat videos - YouTube')", max_length=500)),
                ('url_path', models.CharField(blank=True, default='', help_text="URL path for deeper tracking (e.g., '/watch?v=...')", max_length=1000)),
                ('category', models.CharField(choices=[('productivity', 'Productivity (VS Code, Notion, etc.)'), ('development', 'Development (IDE, Terminal, Git)'), ('communication', 'Communication (Slack, Email, Discord)'), ('social', 'Social Media (Instagram, Twitter, Reddit)'), ('entertainment', 'Entertainment (YouTube, Netflix, Gaming)'), ('ai_tools', 'AI Tools (ChatGPT, Claude, etc.)'), ('browsing', 'General Browsing'), ('system', 'System (Desktop, File Explorer)'), ('other', 'Other')], default='browsing', help_text='Category of this website', max_length=30)),
                ('total_seconds', models.FloatField(default=0, help_text='Total time spent on this domain (seconds)')),
                ('visit_count', models.IntegerField(default=0, help_text='Number of visits to this domain')),
                ('first_seen', models.DateTimeField(blank=True, help_text='First time this site was visited', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time this site was visited', null=True)),
                ('activity_session', models.ForeignKey(help_text='Activity session this usage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='website_usage', to='procrastina_ai.activitysession')),
            ],
            options={
                'verbose_name': 'Website Usage',
                'verbose_name_plural': 'Website Usages',
                'ordering': ['-total_seconds'],
                'unique_together': {('activity_session', 'domain')},
            },
        ),
    ]
