# Generated by Django 5.2.7 on 2026-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0004_activitysession_idleperiod_activitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='focus_change_count',
            field=models.IntegerField(default=0, help_text='Number of application focus switches detected'),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='last_active_app',
            field=models.CharField(blank=True, default='', help_text='Currently or most recently focused application', max_length=255),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='last_idle_started',
            field=models.DateTimeField(blank=True, help_text='When current idle period started (null if not idle)', null=True),
        ),
        migrations.AddField(
            model_name='activitysession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last activity event received'),
        ),
    ]
