# Generated by Django 5.2.7 on 2026-06-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0006_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='disappearance',
            name='explanation_status',
            field=models.CharField(choices=[('pending', 'Pending Explanation'), ('explained', 'Explained by User'), ('unexplained', 'User Chose to Remain a Mystery')], default='pending', help_text='Whether user has explained this disappearance', max_length=20),
        ),
        migrations.AddField(
            model_name='disappearance',
            name='explanation_timestamp',
            field=models.DateTimeField(blank=True, help_text='When user provided the explanation', null=True),
        ),
        migrations.AddField(
            model_name='disappearance',
            name='idle_duration_seconds',
            field=models.FloatField(default=0, help_text='How long the idle period lasted (seconds)'),
        ),
        migrations.AddField(
            model_name='disappearance',
            name='last_active_app',
            field=models.CharField(blank=True, default='', help_text='Application focused before this disappearance', max_length=255),
        ),
        migrations.AddField(
            model_name='disappearance',
            name='last_window_title',
            field=models.CharField(blank=True, default='', help_text='Window title before this disappearance', max_length=500),
        ),
        migrations.AddField(
            model_name='disappearance',
            name='reason_source',
            field=models.CharField(blank=True, choices=[('auto_generated', 'Auto-created from idle detection'), ('user_selected', 'User picked from preset options'), ('custom_text', 'User typed a custom reason')], default='', help_text='How the disappearance reason was determined', max_length=20),
        ),
        migrations.AlterField(
            model_name='disappearance',
            name='disappearance_type',
            field=models.CharField(choices=[('youtube', 'Watching YouTube'), ('laptops', 'Looking At Laptops'), ('ai_tools', 'Researching AI Tools'), ('startup', 'Planning A Startup'), ('comments', 'Reading Comments'), ('other', 'Other (custom location)')], default='other', help_text='Where the user disappeared to', max_length=100),
        ),
    ]
