# Generated by Django 5.2.7 on 2026-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procrastina_ai', '0007_disappearance_explanation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='task_statuses',
            field=models.JSONField(default=dict, help_text='Task completion statuses: {task_name: status_string}'),
        ),
    ]
